GET http://localhost:3000/subscribers

###

GET  http://localhost:3000/all


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    name: "Veda",
    subscribedToChannel: "abc",

}